Added data and staging
appmath8/Intelligent-Placer pull request #1
Opened 2022-09-17 16:48 UTC by appmath8

2022-10-15 13:35 UTC, aVorotnikov commented
Не уверен что фон images/place.jpg неудачный - лучше снять без тени в левом нижнем углу

2022-10-15 16:18 UTC, AleksandrMilanich commented on README.md
> +  - изображение получается при съемке под углом не более 10 гр по оси x,y,z
Будет ли как-то проверяться угол наклона? Что выведет программа, если угол наклона не будет удовлетворять условиям?

2022-10-15 18:16 UTC, levs2001 requested changes
В целом, неплохо. Нужно добавить описание структуры данных для хранения контуров и более подробно расписать проход контура по многоугольнику.

2022-10-15 18:16 UTC, levs2001 commented on README.md
> +        * Выполняется проход контуром по многоугольнику в различных направлениях.
Слишком общо сказано. Хотя бы примерно опиши, как ты это видишь. Начинаем с угла или в центре? Будешь ли ты пытаться крутить предметы?

2022-10-15 18:16 UTC, levs2001 commented on README.md
> +    * Сохраняем контур в соответсвующий пулл для дальнейшего использования.
Добавь, пожалуйста, описание структуры данных, в которой ты будешь хранить контуры. Например, массив точек.

2022-10-23 19:14 UTC, appmath8 commented on README.md
> +  - изображение получается при съемке под углом не более 10 гр по оси x,y,z
На данный момент проверка будет состоять в визуальном осмотре изображений входящих в датасет. Программная реализация данного компонента проверки  в принципе возможна: например по анализу величины тени, отбрасываемой предметом, либо по искажению геометрии самого предмета. - но реализовать это будет трудозатратно.

2022-10-23 19:19 UTC, appmath8 commented on README.md
> +        * Выполняется проход контуром по многоугольнику в различных направлениях.
Спасибо за уточнение. Дополню план детализирующей информацией по этому вопросу

2022-10-23 19:20 UTC, appmath8 commented on README.md
> +    * Сохраняем контур в соответсвующий пулл для дальнейшего использования.
Хорошо, добавлю

2022-10-23 19:23 UTC, appmath8 commented
> Не уверен, что фон images/place.jpg неудачный - лучше снять без теней в левом углу

2022-10-23 19:25 UTC, appmath8 commented
> Не уверен, что фон images/place.jpg неудачный - лучше снять без теней в левом углу

Согласен, заменю текущий фон на фон без тени

2022-10-23 19:30 UTC, merged